[package]
edition = "2021"
name = "mgmt-dfu"
version = "0.1.0"
license = "MIT OR Apache-2.0"

[[bin]]
name = "mgmt-dfu"
path = "src/main.rs"
test = false
bench = false

[dependencies]
cortex-m = { version = "0.7", features = ["inline-asm", "critical-section-single-core"] }
cortex-m-rt = { version = "0.7" }

embassy-executor = { version = "0.9", features = ["arch-cortex-m", "executor-thread", "executor-interrupt"] }
embassy-stm32 = { version = "0.4", features = ["stm32f072cb", "memory-x", "exti", "time-driver-any"] }
embassy-sync = "0.7"
embassy-time = "0.5"
embassy-futures = "0.1"
embassy-usb = { version = "0.6", default-features = false }
embassy-usb-dfu = { version = "0.3", features = ["application", "cortex-m"] }

panic-reset = "0.1"
portable-atomic = { version = "1", features = ["critical-section"] }
static_cell = "2"

[profile.dev]
opt-level = "s"
lto = "fat"
debug = 0
panic = "abort"

[profile.release]
opt-level = "s"
lto = "fat"
debug = 0
panic = "abort"
